gapic_generator_version: 2.40.1
protoc_version: '25.2'
googleapis_committish: 3597f7db2191c00b100400991ef96e52d62f5841
libraries_bom_version: 26.38.0
template_excludes:
  - 'README.md'
  - '.github/release-please.yml'
  - '.github/sync-repo-settings.yaml'
  - '.github/blunderbuss.yml'
  - '.kokoro/nightly/integration.cfg'
  - '.kokoro/build.sh'
  - '.kokoro/requirements.in'
  - '.kokoro/requirements.txt'
  - '.kokoro/presubmit/graalvm-native.cfg'
  - '.kokoro/presubmit/graalvm-native-17.cfg'
libraries:
  - api_shortname: "spanner-jdbc"
    name_pretty: "Google Cloud Spanner JDBC"
    product_documentation: "https://cloud.google.com/spanner/docs/use-oss-jdbc"
    client_documentation: "https://cloud.google.com/java/docs/reference/google-cloud-spanner-jdbc/latest/history"
    release_level: "stable"
    language: "java"
    min_java_version: 8
    repo: "googleapis/java-spanner-jdbc"
    repo_short: "java-spanner-jdbc"
    distribution_name: "com.google.cloud:google-cloud-spanner-jdbc"
    library_type: "OTHER"
    codeowner_team: "@googleapis/api-spanner-java"
    recommended_package: "com.google.cloud.spanner.jdbc"
    GAPICs:
      - google/api #we use a dummy path to produce a no-op
